apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp-deployment
  labels:
    app: kubernetes-bootcamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
        - name: kubernetes-bootcamp
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-nodeport
spec:
  # In a minikube (single-node) deployment, a nodePort servcie load balances requests across pods on
  # the node. That is, in a single-node deployment, nodePort and loadBalancer behave similarly.
  type: NodePort
  selector:
    app: kubernetes-bootcamp
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-lb
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-bootcamp
  ports:
    - port: 8081
      targetPort: 8080
